/* Individual member pages: fictional demo data only. Replace after Secretariat approval. */
(function () {
  "use strict";

  var profiles = {
    "alexei-volkov": {
      type: "person", image: "alexei-volkov.webp",
      kind: { zh: "理事会 · 虚构示例", ru: "Совет · Демонстрационный профиль", en: "Council · Fictional Demo" },
      name: { zh: "阿列克谢·沃尔科夫", ru: "Алексей Волков", en: "Alexei Volkov" },
      role: { zh: "会长", ru: "Президент ассоциации", en: "President" },
      entity: { zh: "俄中电子商务协会理事会", ru: "Совет Российско-Китайской ассоциации электронной коммерции", en: "RCECA Council" },
      location: { zh: "俄罗斯 · 莫斯科", ru: "Москва, Россия", en: "Moscow, Russia" },
      intro: { zh: "本页用于演示会长个人专页的内容结构。正式版本可重点介绍其行业经历、协会愿景、代表性项目及可为会员链接的俄罗斯本土资源。", ru: "Эта страница демонстрирует структуру персонального профиля президента. В официальной версии здесь можно представить отраслевой опыт, видение ассоциации, ключевые проекты и российские ресурсы, доступные членам.", en: "This page demonstrates the structure of a President profile. The confirmed version can highlight industry experience, the Association vision, representative projects and Russian resources available to members." },
      focus: [ {zh:"协会战略",ru:"Стратегия",en:"Association Strategy"}, {zh:"产业协同",ru:"Отраслевая кооперация",en:"Industry Cooperation"}, {zh:"俄罗斯本土网络",ru:"Локальная сеть в России",en:"Russia Local Network"} ],
      background: { zh:"示例：二十余年俄罗斯商业与产业合作经历。", ru:"Демо: более 20 лет российско-китайского делового сотрудничества.", en:"Demo: 20+ years in Russia-China business cooperation." },
      responsibility: { zh:"示例：主持理事会工作，推动协会战略与重大合作。", ru:"Демо: руководство советом, стратегией и ключевыми партнёрствами.", en:"Demo: chairing the Council, strategy and major partnerships." },
      cooperation: { zh:"示例：政府与协会交流、产业园区及大型企业资源对接。", ru:"Демо: госструктуры, ассоциации, индустриальные парки и крупные компании.", en:"Demo: public bodies, associations, industrial parks and major enterprises." },
      sector: { zh:"协会治理 / 产业合作", ru:"Управление / отраслевое сотрудничество", en:"Governance / Industry Cooperation" }, markets:{zh:"俄罗斯、中国",ru:"Россия, Китай",en:"Russia, China"}, languages:{zh:"俄语、英语",ru:"Русский, английский",en:"Russian, English"}
    },
    "chen-wei": {
      type:"person", image:"chen-wei.webp", kind:{zh:"理事会 · 虚构示例",ru:"Совет · Демонстрационный профиль",en:"Council · Fictional Demo"},
      name:{zh:"陈伟",ru:"Чэнь Вэй",en:"Chen Wei"}, role:{zh:"执行会长",ru:"Исполнительный президент",en:"Executive President"},
      entity:{zh:"俄中电子商务协会理事会",ru:"Совет Российско-Китайской ассоциации электронной коммерции",en:"RCECA Council"}, location:{zh:"中国 · 深圳",ru:"Шэньчжэнь, Китай",en:"Shenzhen, China"},
      intro:{zh:"本页演示执行会长的独立介绍方式，突出协会运营统筹、中国会员企业服务以及跨境电商生态合作。正式内容应由本人或秘书处审核。",ru:"Демонстрационная страница исполнительного президента: операционное управление, сервис для китайских членов и развитие экосистемы трансграничной торговли. Официальный текст требует согласования.",en:"This demo profile illustrates how to present the Executive President, focusing on operations, service for Chinese member companies and cross-border e-commerce ecosystem partnerships. Final copy requires approval."},
      focus:[{zh:"协会运营",ru:"Операционное управление",en:"Association Operations"},{zh:"企业出海",ru:"Выход на рынок",en:"Market Entry"},{zh:"平台合作",ru:"Работа с платформами",en:"Platform Partnerships"}],
      background:{zh:"示例：长期从事跨境电商与中国品牌国际化。",ru:"Демо: опыт в e-commerce и интернационализации китайских брендов.",en:"Demo: cross-border e-commerce and Chinese brand internationalization."},
      responsibility:{zh:"示例：落实理事会决议，统筹中国区运营与重点项目。",ru:"Демо: реализация решений совета и управление ключевыми проектами в Китае.",en:"Demo: implementing Council decisions and leading China operations."},
      cooperation:{zh:"示例：平台招商、品牌孵化、产业带与服务商协同。",ru:"Демо: маркетплейсы, развитие брендов, промышленные кластеры и сервисные партнёры.",en:"Demo: marketplaces, brand incubation, industrial clusters and service partners."},
      sector:{zh:"跨境电商 / 运营管理",ru:"E-commerce / управление",en:"E-commerce / Operations"},markets:{zh:"中国、俄罗斯",ru:"Китай, Россия",en:"China, Russia"},languages:{zh:"中文、英语",ru:"Китайский, английский",en:"Chinese, English"}
    },
    "natalia-sokolova": {
      type:"person", image:"natalia-sokolova.webp", kind:{zh:"理事会 · 虚构示例",ru:"Совет · Демонстрационный профиль",en:"Council · Fictional Demo"},
      name:{zh:"娜塔莉娅·索科洛娃",ru:"Наталья Соколова",en:"Natalia Sokolova"}, role:{zh:"副会长",ru:"Вице-президент",en:"Vice President"},
      entity:{zh:"俄中电子商务协会理事会",ru:"Совет Российско-Китайской ассоциации электронной коммерции",en:"RCECA Council"},location:{zh:"俄罗斯 · 圣彼得堡",ru:"Санкт-Петербург, Россия",en:"St. Petersburg, Russia"},
      intro:{zh:"本页演示副会长个人专页，可用于呈现俄罗斯渠道合作、品牌本地化、公共关系及其负责的专项委员会工作。",ru:"Демонстрационный профиль вице-президента для представления российских каналов, локализации брендов, внешних связей и работы профильного комитета.",en:"This demo Vice President profile can present Russian channel partnerships, brand localization, public affairs and committee responsibilities."},
      focus:[{zh:"渠道合作",ru:"Каналы продаж",en:"Channel Partnerships"},{zh:"品牌本地化",ru:"Локализация брендов",en:"Brand Localization"},{zh:"公共关系",ru:"Внешние связи",en:"Public Affairs"}],
      background:{zh:"示例：俄罗斯零售渠道与国际品牌合作经验。",ru:"Демо: опыт в российском ритейле и международных брендах.",en:"Demo: Russian retail channels and international brands."},responsibility:{zh:"示例：推动俄方合作伙伴关系与会员本地化支持。",ru:"Демо: партнёрства в России и поддержка локализации членов.",en:"Demo: Russia-side partnerships and member localization support."},cooperation:{zh:"示例：区域经销、品牌传播、行业活动与机构交流。",ru:"Демо: дистрибуция, коммуникации бренда, отраслевые события и институциональные связи.",en:"Demo: distribution, brand communications, industry events and institutional relations."},
      sector:{zh:"品牌 / 渠道",ru:"Бренды / каналы",en:"Brands / Channels"},markets:{zh:"俄罗斯、欧亚经济联盟",ru:"Россия, ЕАЭС",en:"Russia, EAEU"},languages:{zh:"俄语、英语",ru:"Русский, английский",en:"Russian, English"}
    },
    "wang-haoran": {
      type:"person",image:"wang-haoran.webp",kind:{zh:"理事会 · 虚构示例",ru:"Совет · Демонстрационный профиль",en:"Council · Fictional Demo"},name:{zh:"王浩然",ru:"Ван Хаожань",en:"Wang Haoran"},role:{zh:"常务理事",ru:"Член президиума",en:"Executive Council Member"},entity:{zh:"俄中电子商务协会理事会",ru:"Совет Российско-Китайской ассоциации электронной коммерции",en:"RCECA Council"},location:{zh:"中国 · 义乌",ru:"Иу, Китай",en:"Yiwu, China"},
      intro:{zh:"本页演示常务理事专页，重点展示跨境供应链、海外仓和平台履约方面的实践能力，以及可与会员协同的资源。",ru:"Демонстрационная страница члена президиума с акцентом на трансграничные поставки, зарубежные склады, фулфилмент и ресурсы для совместной работы.",en:"This demo Executive Council Member page highlights cross-border supply chains, overseas warehousing, platform fulfillment and resources that can support members."},
      focus:[{zh:"跨境供应链",ru:"Трансграничные поставки",en:"Cross-border Supply Chain"},{zh:"海外仓",ru:"Зарубежные склады",en:"Overseas Warehousing"},{zh:"平台履约",ru:"Фулфилмент",en:"Marketplace Fulfillment"}],background:{zh:"示例：多年中俄物流与仓配网络建设经验。",ru:"Демо: многолетний опыт в логистике и складской сети Китай–Россия.",en:"Demo: years of China-Russia logistics and warehousing experience."},responsibility:{zh:"示例：参与理事会常务工作，牵头供应链专项合作。",ru:"Демо: текущая работа совета и руководство проектами по цепочкам поставок.",en:"Demo: Council operations and supply-chain initiatives."},cooperation:{zh:"示例：集货、清关、海外仓、尾程配送与库存协同。",ru:"Демо: консолидация, таможня, склады, последняя миля и управление запасами.",en:"Demo: consolidation, customs, warehousing, last mile and inventory coordination."},sector:{zh:"物流 / 供应链",ru:"Логистика / цепочки поставок",en:"Logistics / Supply Chain"},markets:{zh:"中国、俄罗斯、中亚",ru:"Китай, Россия, Центральная Азия",en:"China, Russia, Central Asia"},languages:{zh:"中文、英语",ru:"Китайский, английский",en:"Chinese, English"}
    },
    "irina-petrova": {
      type:"person",image:"irina-petrova.webp",kind:{zh:"理事会 · 虚构示例",ru:"Совет · Демонстрационный профиль",en:"Council · Fictional Demo"},name:{zh:"伊琳娜·彼得罗娃",ru:"Ирина Петрова",en:"Irina Petrova"},role:{zh:"理事",ru:"Член совета",en:"Council Member"},entity:{zh:"俄中电子商务协会理事会",ru:"Совет Российско-Китайской ассоциации электронной коммерции",en:"RCECA Council"},location:{zh:"俄罗斯 · 莫斯科",ru:"Москва, Россия",en:"Moscow, Russia"},
      intro:{zh:"本页演示理事个人专页，可用于介绍其 EAC 合规、俄罗斯公司法务和跨境交易风险管理经验。任何正式资质与案例均需提供证明材料。",ru:"Демонстрационный профиль члена совета для описания опыта в EAC, российском корпоративном праве и рисках трансграничных сделок. Официальные квалификации требуют подтверждения.",en:"This demo Council Member profile presents possible experience in EAC compliance, Russian corporate law and cross-border transaction risk. Any official qualifications and cases require evidence."},
      focus:[{zh:"EAC 合规",ru:"Комплаенс EAC",en:"EAC Compliance"},{zh:"公司法务",ru:"Корпоративное право",en:"Corporate Law"},{zh:"交易风险",ru:"Риски сделок",en:"Transaction Risk"}],background:{zh:"示例：俄罗斯市场准入与企业合规顾问经历。",ru:"Демо: консультирование по выходу на рынок и корпоративному комплаенсу.",en:"Demo: Russian market access and corporate compliance advisory."},responsibility:{zh:"示例：为协会标准、合同和风险事项提供专业建议。",ru:"Демо: консультации по стандартам, договорам и рискам ассоциации.",en:"Demo: advising on Association standards, contracts and risk."},cooperation:{zh:"示例：认证法规、合同审查、主体设立与争议预防。",ru:"Демо: сертификация, договоры, регистрация компаний и профилактика споров.",en:"Demo: certification, contract review, company setup and dispute prevention."},sector:{zh:"法律 / 合规",ru:"Право / комплаенс",en:"Legal / Compliance"},markets:{zh:"俄罗斯、欧亚经济联盟",ru:"Россия, ЕАЭС",en:"Russia, EAEU"},languages:{zh:"俄语、英语",ru:"Русский, английский",en:"Russian, English"}
    },
    "li-na": {
      type:"person",image:"li-na.webp",kind:{zh:"秘书处 · 虚构示例",ru:"Секретариат · Демонстрационный профиль",en:"Secretariat · Fictional Demo"},name:{zh:"李娜",ru:"Ли На",en:"Li Na"},role:{zh:"秘书长",ru:"Генеральный секретарь",en:"Secretary-General"},entity:{zh:"俄中电子商务协会秘书处",ru:"Секретариат ассоциации",en:"RCECA Secretariat"},location:{zh:"中国 · 深圳 / 俄罗斯 · 莫斯科",ru:"Шэньчжэнь / Москва",en:"Shenzhen / Moscow"},
      intro:{zh:"本页演示秘书长个人介绍，可呈现秘书处统筹、年度工作计划、会员项目和中俄团队协作等日常职责。",ru:"Демонстрационный профиль генерального секретаря: координация секретариата, годовой план, программы для членов и взаимодействие команд России и Китая.",en:"This demo Secretary-General profile can present Secretariat coordination, annual planning, member programs and China-Russia team collaboration."},
      focus:[{zh:"秘书处统筹",ru:"Координация секретариата",en:"Secretariat Coordination"},{zh:"年度计划",ru:"Годовое планирование",en:"Annual Planning"},{zh:"会员项目",ru:"Программы для членов",en:"Member Programs"}],background:{zh:"示例：跨境项目管理与双边商务组织运营。",ru:"Демо: управление трансграничными проектами и деловыми организациями.",en:"Demo: cross-border project and bilateral business organization management."},responsibility:{zh:"示例：负责秘书处日常管理、会议组织与决议执行。",ru:"Демо: ежедневная работа секретариата, заседания и исполнение решений.",en:"Demo: daily Secretariat management, meetings and decision execution."},cooperation:{zh:"示例：会员项目、合作备忘录、活动与跨语言内容协调。",ru:"Демо: проекты членов, меморандумы, мероприятия и многоязычный контент.",en:"Demo: member programs, MOUs, events and multilingual content coordination."},sector:{zh:"协会运营 / 项目管理",ru:"Управление ассоциацией / проекты",en:"Association Operations / Projects"},markets:{zh:"中国、俄罗斯",ru:"Китай, Россия",en:"China, Russia"},languages:{zh:"中文、英语、俄语",ru:"Китайский, английский, русский",en:"Chinese, English, Russian"}
    },
    "mikhail-orlov": {
      type:"person",image:"mikhail-orlov.webp",kind:{zh:"秘书处 · 虚构示例",ru:"Секретариат · Демонстрационный профиль",en:"Secretariat · Fictional Demo"},name:{zh:"米哈伊尔·奥尔洛夫",ru:"Михаил Орлов",en:"Mikhail Orlov"},role:{zh:"副秘书长",ru:"Заместитель генерального секретаря",en:"Deputy Secretary-General"},entity:{zh:"俄中电子商务协会秘书处",ru:"Секретариат ассоциации",en:"RCECA Secretariat"},location:{zh:"俄罗斯 · 莫斯科",ru:"Москва, Россия",en:"Moscow, Russia"},
      intro:{zh:"本页演示副秘书长介绍，突出俄方事务协调、活动执行、合作伙伴联络及会员落地支持等工作。",ru:"Демонстрационный профиль заместителя генерального секретаря: координация российской стороны, мероприятия, партнёрские связи и поддержка членов.",en:"This demo Deputy Secretary-General profile focuses on Russia-side coordination, events, partner relations and member implementation support."},focus:[{zh:"俄方协调",ru:"Координация в России",en:"Russia Coordination"},{zh:"活动执行",ru:"Мероприятия",en:"Event Delivery"},{zh:"伙伴联络",ru:"Партнёрские связи",en:"Partner Relations"}],background:{zh:"示例：俄中商务活动、代表团与机构合作。",ru:"Демо: российско-китайские деловые события, делегации и институциональные связи.",en:"Demo: Russia-China business events, delegations and institutional relations."},responsibility:{zh:"示例：协助秘书长推进俄方日常事务和重点活动。",ru:"Демо: поддержка российской операционной работы и ключевых мероприятий.",en:"Demo: supporting Russia-side operations and key events."},cooperation:{zh:"示例：商务考察、场地机构、专家和本地服务资源。",ru:"Демо: бизнес-миссии, площадки, эксперты и локальные сервисы.",en:"Demo: business missions, venues, experts and local service resources."},sector:{zh:"国际合作 / 活动",ru:"Международное сотрудничество / события",en:"International Cooperation / Events"},markets:{zh:"俄罗斯、中国",ru:"Россия, Китай",en:"Russia, China"},languages:{zh:"俄语、英语",ru:"Русский, английский",en:"Russian, English"}
    },
    "zhao-qing": {
      type:"person",image:"zhao-qing.webp",kind:{zh:"秘书处 · 虚构示例",ru:"Секретариат · Демонстрационный профиль",en:"Secretariat · Fictional Demo"},name:{zh:"赵晴",ru:"Чжао Цин",en:"Zhao Qing"},role:{zh:"会员部主管",ru:"Руководитель отдела по работе с членами",en:"Head of Membership"},entity:{zh:"俄中电子商务协会会员部",ru:"Отдел по работе с членами",en:"RCECA Membership Department"},location:{zh:"中国 · 深圳",ru:"Шэньчжэнь, Китай",en:"Shenzhen, China"},
      intro:{zh:"本页演示会员部主管个人介绍，重点呈现入会服务、会员需求分层、权益交付和社群运营。",ru:"Демонстрационный профиль руководителя отдела по работе с членами: приём, сегментация потребностей, реализация преимуществ и развитие сообщества.",en:"This demo Head of Membership profile presents onboarding, member needs segmentation, benefits delivery and community operations."},focus:[{zh:"会员入会",ru:"Приём членов",en:"Member Onboarding"},{zh:"权益交付",ru:"Реализация преимуществ",en:"Benefits Delivery"},{zh:"社群运营",ru:"Развитие сообщества",en:"Community Operations"}],background:{zh:"示例：企业客户成功、会员服务与商务社群运营。",ru:"Демо: customer success, членский сервис и деловые сообщества.",en:"Demo: customer success, member service and business communities."},responsibility:{zh:"示例：维护会员档案，跟进需求，协调权益和活动。",ru:"Демо: профили членов, сопровождение запросов, координация преимуществ и мероприятий.",en:"Demo: member records, needs follow-up, benefits and events coordination."},cooperation:{zh:"示例：入会咨询、资源需求、活动报名与资料更新。",ru:"Демо: консультации, запросы ресурсов, регистрация на события и обновление профилей.",en:"Demo: membership inquiries, resource needs, event registration and profile updates."},sector:{zh:"会员服务 / 社群运营",ru:"Членский сервис / сообщество",en:"Member Service / Community"},markets:{zh:"中国、俄罗斯",ru:"Китай, Россия",en:"China, Russia"},languages:{zh:"中文、英语",ru:"Китайский, английский",en:"Chinese, English"}
    },
    "north-star-digital": {
      type:"company",mark:"NS",kind:{zh:"企业会员 · 虚构示例",ru:"Корпоративный член · Демонстрационный профиль",en:"Corporate Member · Fictional Demo"},name:{zh:"中俄北辰数字贸易有限公司",ru:"Компания «Северная звезда Диджитал»",en:"North Star Digital Trade Co."},role:{zh:"跨境电商本地化运营",ru:"Локализация e-commerce",en:"Cross-border E-commerce Localization"},entity:{zh:"示例会员单位",ru:"Демонстрационная организация",en:"Demo Member Organization"},location:{zh:"中国 · 杭州 / 俄罗斯 · 莫斯科",ru:"Ханчжоу / Москва",en:"Hangzhou / Moscow"},
      intro:{zh:"这是虚构企业会员专页示例，展示企业简介、核心能力、市场覆盖和希望对接的合作方向。正式版本应使用营业执照名称、审核后的品牌介绍和真实案例。",ru:"Вымышленный пример страницы корпоративного члена: профиль компании, компетенции, рынки и направления сотрудничества. В официальной версии нужны юридическое название, согласованный текст и реальные кейсы.",en:"This fictional corporate member page demonstrates company overview, capabilities, market coverage and partnership interests. The final version should use the legal name, approved brand copy and verified cases."},focus:[{zh:"OZON / WB 运营",ru:"OZON / WB",en:"OZON / WB Operations"},{zh:"内容本地化",ru:"Локализация контента",en:"Content Localization"},{zh:"品牌增长",ru:"Рост брендов",en:"Brand Growth"}],background:{zh:"示例：为消费品牌提供俄罗斯平台入驻与日常运营。",ru:"Демо: запуск и управление потребительскими брендами на маркетплейсах России.",en:"Demo: marketplace launch and operations for consumer brands in Russia."},responsibility:{zh:"示例：作为企业会员参与协会活动并分享平台运营经验。",ru:"Демо: участие в мероприятиях и обмен опытом работы на маркетплейсах.",en:"Demo: Association participation and marketplace operations knowledge-sharing."},cooperation:{zh:"示例：寻找中国品牌、内容团队和俄罗斯渠道合作伙伴。",ru:"Демо: китайские бренды, контент-команды и российские каналы.",en:"Demo: Chinese brands, content teams and Russian channel partners."},sector:{zh:"跨境电商",ru:"Трансграничная e-commerce",en:"Cross-border E-commerce"},markets:{zh:"俄罗斯、中国",ru:"Россия, Китай",en:"Russia, China"},languages:{zh:"中文、俄语、英语",ru:"Китайский, русский, английский",en:"Chinese, Russian, English"}
    },
    "volga-home": {
      type:"company",mark:"VH",kind:{zh:"机构会员 · 虚构示例",ru:"Институциональный член · Демонстрационный профиль",en:"Institutional Member · Fictional Demo"},name:{zh:"伏尔加家居供应链联盟",ru:"Альянс поставок «Волга Дом»",en:"Volga Home Supply Alliance"},role:{zh:"家居制造与区域分销协作",ru:"Производство и дистрибуция товаров для дома",en:"Home Manufacturing & Regional Distribution"},entity:{zh:"示例会员机构",ru:"Демонстрационная организация",en:"Demo Member Organization"},location:{zh:"中国 · 佛山 / 俄罗斯 · 喀山",ru:"Фошань / Казань",en:"Foshan / Kazan"},
      intro:{zh:"这是虚构机构会员示例，用于展示产业联盟、商会或园区类会员的组织规模、产业资源与供需合作方向。",ru:"Вымышленный пример институционального члена для отраслевого альянса, палаты или парка: масштаб, ресурсы и направления кооперации.",en:"This fictional institutional member profile demonstrates how an industry alliance, chamber or park can present scale, resources and supply-demand collaboration."},focus:[{zh:"家居产业带",ru:"Кластер товаров для дома",en:"Home-goods Cluster"},{zh:"区域经销",ru:"Региональная дистрибуция",en:"Regional Distribution"},{zh:"联合采购",ru:"Совместные закупки",en:"Joint Procurement"}],background:{zh:"示例：连接中国家居制造集群与俄罗斯区域经销商。",ru:"Демо: связь китайских производственных кластеров с региональными дистрибьюторами России.",en:"Demo: linking Chinese manufacturing clusters with Russian regional distributors."},responsibility:{zh:"示例：组织会员企业参加供需对接和行业考察。",ru:"Демо: организация B2B-встреч и отраслевых визитов.",en:"Demo: organizing member companies for B2B matching and industry visits."},cooperation:{zh:"示例：家具、照明、建材、仓储与本地展示渠道。",ru:"Демо: мебель, свет, стройматериалы, склады и локальные шоурумы.",en:"Demo: furniture, lighting, building materials, warehousing and local showrooms."},sector:{zh:"家居 / 供应链",ru:"Товары для дома / поставки",en:"Home Goods / Supply Chain"},markets:{zh:"中国、俄罗斯伏尔加联邦区",ru:"Китай, Приволжский федеральный округ",en:"China, Volga Federal District"},languages:{zh:"中文、俄语",ru:"Китайский, русский",en:"Chinese, Russian"}
    },
    "silkroad-compliance": {
      type:"company",mark:"SC",kind:{zh:"企业会员 · 虚构示例",ru:"Корпоративный член · Демонстрационный профиль",en:"Corporate Member · Fictional Demo"},name:{zh:"丝路欧亚合规服务中心",ru:"Центр комплаенса «Шёлковый путь — Евразия»",en:"Silk Road Eurasia Compliance Center"},role:{zh:"EAC 认证与市场准入支持",ru:"Сертификация EAC и доступ на рынок",en:"EAC Certification & Market Access"},entity:{zh:"示例会员单位",ru:"Демонстрационная организация",en:"Demo Member Organization"},location:{zh:"中国 · 深圳 / 俄罗斯 · 莫斯科",ru:"Шэньчжэнь / Москва",en:"Shenzhen / Moscow"},
      intro:{zh:"这是虚构合规服务企业会员示例，用于展示专业服务能力、适用品类、服务区域和会员合作边界。正式页面不得在未核验证据的情况下展示资质、客户或成功案例。",ru:"Вымышленный пример компании в сфере комплаенса: компетенции, категории, география и рамки сотрудничества. Нельзя публиковать квалификации, клиентов или кейсы без проверки.",en:"This fictional compliance-service member profile demonstrates capabilities, product categories, geography and collaboration boundaries. Qualifications, clients and cases must not be published without verification."},focus:[{zh:"EAC 认证",ru:"Сертификация EAC",en:"EAC Certification"},{zh:"标签审核",ru:"Проверка маркировки",en:"Label Review"},{zh:"准入咨询",ru:"Консультации по доступу",en:"Market-access Advisory"}],background:{zh:"示例：消费品与工业品欧亚经济联盟市场准入支持。",ru:"Демо: доступ потребительских и промышленных товаров на рынок ЕАЭС.",en:"Demo: EAEU market-access support for consumer and industrial products."},responsibility:{zh:"示例：参与协会合规培训和会员基础咨询。",ru:"Демо: участие в обучении по комплаенсу и базовых консультациях для членов.",en:"Demo: compliance training and initial member consultations."},cooperation:{zh:"示例：检测实验室、认证机构、法规翻译与标签制作。",ru:"Демо: лаборатории, органы сертификации, перевод регламентов и маркировка.",en:"Demo: laboratories, certification bodies, regulatory translation and labeling."},sector:{zh:"认证 / 合规服务",ru:"Сертификация / комплаенс",en:"Certification / Compliance"},markets:{zh:"俄罗斯、欧亚经济联盟",ru:"Россия, ЕАЭС",en:"Russia, EAEU"},languages:{zh:"中文、俄语、英语",ru:"Китайский, русский, английский",en:"Chinese, Russian, English"}
    }
  };

  function esc(value) {
    return String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
  function attr(value) {
    return "data-zh=\"" + esc(value.zh) + "\" data-ru=\"" + esc(value.ru) + "\" data-en=\"" + esc(value.en) + "\"";
  }
  function text(tag, cls, value) {
    return "<" + tag + (cls ? " class=\"" + cls + "\"" : "") + " " + attr(value) + ">" + esc(value.zh) + "</" + tag + ">";
  }
  function focusTags(items) {
    return items.map(function (item) { return text("span", "", item); }).join("");
  }
  function profileImage(profile) {
    if (profile.type === "company") {
      return "<div class=\"profile-portrait profile-company-portrait\"><div class=\"company-mark\">" + esc(profile.mark) + "</div></div>";
    }
    return "<div class=\"profile-portrait\"><img src=\"../img/members/" + esc(profile.image) + "\" alt=\"\"></div>";
  }

  var id = document.body.getAttribute("data-profile-id");
  var profile = profiles[id];
  if (!profile) {
    document.body.innerHTML = "<main class=\"profile-page\"><div class=\"container\"><p>Profile not found.</p><a class=\"btn btn-gold\" href=\"../members.html\">Back</a></div></main>";
    return;
  }

  var title = document.querySelector("title");
  if (title) {
    title.setAttribute("data-zh", profile.name.zh + " — 协会成员");
    title.setAttribute("data-ru", profile.name.ru + " — Руководство и члены");
    title.setAttribute("data-en", profile.name.en + " — Association Members");
    title.textContent = profile.name.zh + " — 协会成员";
  }

  var demoTitle = {zh:"演示资料 · 待秘书处确认",ru:"Демонстрационные данные · Требуется подтверждение",en:"Demo content · Confirmation required"};
  var demoBody = {zh:"本页全部人物、单位、职务、照片与文字均为虚构示例，不代表真实任职或会员关系，正式发布前必须整体替换。",ru:"Все данные, должности, фотографии и тексты на этой странице вымышлены и не отражают реальный состав. Перед публикацией их необходимо полностью заменить.",en:"All names, roles, images and copy on this page are fictional samples and do not represent real appointments or membership. Replace everything before publication."};
  var overviewTitle = {zh:"成员简介",ru:"Профиль",en:"Profile Overview"};
  var contributionTitle = {zh:"可展示的专业信息",ru:"Профессиональная информация",en:"Professional Information"};
  var bgTitle = {zh:"专业背景",ru:"Профессиональный опыт",en:"Background"};
  var dutyTitle = {zh:"协会职责",ru:"Роль в ассоциации",en:"Association Role"};
  var coopTitle = {zh:"合作方向",ru:"Направления сотрудничества",en:"Cooperation"};

  document.body.innerHTML =
    "<header class=\"site-header\"><div class=\"header-inner\">" +
      "<a class=\"logo\" href=\"../index.html\"><img class=\"logo-img\" src=\"../img/logo-mark.png\" alt=\"RCECA\" width=\"40\" height=\"40\"><span class=\"logo-text\">" +
      text("span","logo-line1",{zh:"俄中电子商务协会",ru:"Ассоциация «Россия — Китай»",en:"Russia-China E-Commerce"}) + text("span","logo-line2",{zh:"Russia-China E-Commerce Association",ru:"Электронная коммерция",en:"Association"}) + "</span></a>" +
      "<nav class=\"main-nav\"><ul>" +
      "<li><a href=\"../index.html\" data-nav=\"home\" " + attr({zh:"首页",ru:"Главная",en:"Home"}) + ">首页</a></li>" +
      "<li><a href=\"../about.html\" data-nav=\"about\" " + attr({zh:"关于协会",ru:"Об ассоциации",en:"About"}) + ">关于协会</a></li>" +
      "<li><a href=\"../membership.html\" data-nav=\"membership\" " + attr({zh:"会员体系",ru:"Членство",en:"Membership"}) + ">会员体系</a></li>" +
      "<li><a href=\"../members.html\" data-nav=\"members\" " + attr({zh:"协会成员",ru:"Руководство и члены",en:"Association Members"}) + ">协会成员</a></li>" +
      "<li><a href=\"../business.html\" data-nav=\"business\" " + attr({zh:"业务板块",ru:"Направления",en:"Business"}) + ">业务板块</a></li>" +
      "<li><a href=\"../network.html\" data-nav=\"network\" " + attr({zh:"分会网络",ru:"Сеть отделений",en:"Network"}) + ">分会网络</a></li>" +
      "<li><a href=\"../contact.html\" data-nav=\"contact\" " + attr({zh:"联系我们",ru:"Контакты",en:"Contact"}) + ">联系我们</a></li>" +
      "</ul></nav><div style=\"display:flex;align-items:center;gap:12px\"><div class=\"lang-switch\" role=\"group\" aria-label=\"Language\"><button class=\"lang-btn active\" data-lang=\"zh\" aria-pressed=\"true\">中文</button><button class=\"lang-btn\" data-lang=\"ru\" aria-pressed=\"false\">Рус</button><button class=\"lang-btn\" data-lang=\"en\" aria-pressed=\"false\">EN</button></div><button class=\"burger\" aria-label=\"Menu\" aria-expanded=\"false\"><span></span><span></span><span></span></button></div>" +
    "</div></header>" +
    "<main class=\"profile-page\"><div class=\"container\">" +
      "<nav class=\"breadcrumb\" aria-label=\"Breadcrumb\"><a href=\"../members.html\" " + attr({zh:"协会成员",ru:"Руководство и члены",en:"Association Members"}) + ">协会成员</a><span class=\"breadcrumb-sep\">/</span>" + text("span","",profile.name) + "</nav>" +
      "<article class=\"profile-hero-card\">" + profileImage(profile) + "<div class=\"profile-hero-copy\">" + text("div","profile-kind",profile.kind) + text("h1","profile-name",profile.name) + text("div","profile-role",profile.role) + text("p","profile-lead",profile.intro) + "<div class=\"profile-meta\"><span><i></i>" + text("span","",profile.entity) + "</span><span><i></i>" + text("span","",profile.location) + "</span></div></div></article>" +
      "<div class=\"demo-notice\"><div class=\"demo-notice-mark\">!</div><div>" + text("strong","",demoTitle) + text("span","",demoBody) + "</div></div>" +
      "<div class=\"profile-content\"><div>" +
        "<section class=\"profile-panel\">" + text("h2","",overviewTitle) + text("p","",profile.intro) + "<div class=\"profile-focus\">" + focusTags(profile.focus) + "</div></section>" +
        "<section class=\"profile-panel\">" + text("h2","",contributionTitle) + "<div class=\"profile-contrib\"><div class=\"profile-contrib-item\">" + text("b","",bgTitle) + text("span","",profile.background) + "</div><div class=\"profile-contrib-item\">" + text("b","",dutyTitle) + text("span","",profile.responsibility) + "</div><div class=\"profile-contrib-item\">" + text("b","",coopTitle) + text("span","",profile.cooperation) + "</div></div></section>" +
      "</div><aside><section class=\"profile-panel\"><ul class=\"profile-facts\"><li>" + text("small","",{zh:"所属类别",ru:"Категория",en:"Category"}) + text("strong","",profile.kind) + "</li><li>" + text("small","",{zh:"行业领域",ru:"Сфера",en:"Sector"}) + text("strong","",profile.sector) + "</li><li>" + text("small","",{zh:"主要市场",ru:"Рынки",en:"Markets"}) + text("strong","",profile.markets) + "</li><li>" + text("small","",{zh:"工作语言",ru:"Рабочие языки",en:"Working Languages"}) + text("strong","",profile.languages) + "</li><li>" + text("small","",{zh:"资料状态",ru:"Статус данных",en:"Content Status"}) + text("strong","",{zh:"演示占位 · 未确认",ru:"Демо · Не подтверждено",en:"Demo · Unconfirmed"}) + "</li></ul></section></aside></div>" +
      "<div class=\"profile-back\"><a class=\"btn btn-ghost\" href=\"../members.html\" " + attr({zh:"← 返回协会成员",ru:"← Вернуться к списку",en:"← Back to Association Members"}) + ">← 返回协会成员</a></div>" +
    "</div></main>" +
    "<footer class=\"site-footer\"><div class=\"container footer-grid\"><div class=\"footer-brand\"><a class=\"logo\" href=\"../index.html\"><img class=\"logo-img\" src=\"../img/logo-mark.png\" alt=\"RCECA\" width=\"40\" height=\"40\"><span class=\"logo-text\">" + text("span","logo-line1",{zh:"俄中电子商务协会",ru:"Ассоциация «Россия — Китай»",en:"Russia-China E-Commerce"}) + text("span","logo-line2",{zh:"Russia-China E-Commerce Association",ru:"Электронная коммерция",en:"Association"}) + "</span></a>" + text("p","footer-desc",{zh:"搭建中俄数字贸易桥梁——赋能会员、链接中俄、共赢未来。",ru:"Мост цифровой торговли между Россией и Китаем.",en:"The bridge of Russia-China digital trade."}) + "</div><div><div class=\"footer-h\" " + attr({zh:"快速导航",ru:"Навигация",en:"Navigation"}) + ">快速导航</div><ul class=\"footer-links\"><li><a href=\"../about.html\" " + attr({zh:"关于协会",ru:"Об ассоциации",en:"About"}) + ">关于协会</a></li><li><a href=\"../membership.html\" " + attr({zh:"会员体系",ru:"Членство",en:"Membership"}) + ">会员体系</a></li><li><a href=\"../members.html\" " + attr({zh:"协会成员",ru:"Руководство и члены",en:"Association Members"}) + ">协会成员</a></li><li><a href=\"../contact.html\" " + attr({zh:"联系我们",ru:"Контакты",en:"Contact"}) + ">联系我们</a></li></ul></div><div><div class=\"footer-h\" " + attr({zh:"联系方式与资料说明",ru:"Контакты и данные",en:"Contact & Content Notice"}) + ">联系方式与资料说明</div><ul class=\"footer-contact\"><li><i>◆</i><a href=\"mailto:gujiamei@rceca.org\" " + attr({zh:"邮箱：gujiamei@rceca.org",ru:"Электронная почта: gujiamei@rceca.org",en:"Email: gujiamei@rceca.org"}) + ">邮箱：gujiamei@rceca.org</a></li></ul>" + text("p","footer-desc",demoBody) + "</div></div><div class=\"foot-bottom\">© <span data-year>2026</span> " + text("span","",{zh:"俄中电子商务协会 · 版权所有",ru:"Российско-Китайская ассоциация электронной коммерции. Все права защищены.",en:"Russia-China E-Commerce Association. All rights reserved."}) + "</div></footer>";
})();
