<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/cms/layout.php';
$user=require_login(); $action=(string)($_GET['action']??'list'); $id=(int)($_GET['id']??0);

function member_photo(array $file): string
{
    if (($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK) { throw new RuntimeException('照片上传失败。'); }
    if ((int)$file['size']<1 || (int)$file['size']>5*1024*1024) { throw new RuntimeException('照片必须在 5MB 以内。'); }
    $mime=(new finfo(FILEINFO_MIME_TYPE))->file((string)$file['tmp_name']); $map=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
    if (!isset($map[$mime])) { throw new RuntimeException('照片仅支持 JPG、PNG 或 WebP。'); }
    $directory=cms_upload_root().'/members'; if(!is_dir($directory)&&!mkdir($directory,0750,true)&&!is_dir($directory)){throw new RuntimeException('无法创建照片目录。');}
    $name=bin2hex(random_bytes(16)).'.'.$map[$mime]; if(!move_uploaded_file((string)$file['tmp_name'],$directory.'/'.$name)){throw new RuntimeException('照片保存失败。');} chmod($directory.'/'.$name,0640); return '/uploads/members/'.$name;
}

if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf(); $op=(string)($_POST['operation']??'');
    if($op==='delete'){$target=(int)($_POST['id']??0);$s=db()->prepare('UPDATE members SET deleted_at=?,deleted_by=?,updated_at=? WHERE id=? AND deleted_at IS NULL');$s->execute([now_utc(),$user['id'],now_utc(),$target]);audit('member_delete','member',$target);flash('success','会员档案已移入回收站。');redirect('/admin/members.php');}
    if($op==='save'){
        $target=(int)($_POST['id']??0);$slug=slugify((string)($_POST['slug']??''));$status=($_POST['status']??'')==='published'?'published':'draft';$nameZh=trim((string)($_POST['name_zh']??''));$nameRu=trim((string)($_POST['name_ru']??''));$nameEn=trim((string)($_POST['name_en']??''));
        try{
            if($slug===''||!preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/',$slug)){throw new RuntimeException('页面标识只能使用小写英文、数字和连字符。');}
            if($nameZh===''){throw new RuntimeException('中文名称不能为空。');} if($status==='published'&&($nameRu===''||$nameEn==='')){throw new RuntimeException('发布前必须填写中、俄、英三语名称。');}
            $photo=null;if(!empty($_FILES['photo'])&&($_FILES['photo']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$photo=member_photo($_FILES['photo']);}
            $fields=['slug'=>$slug,'member_type'=>in_array(($_POST['member_type']??''),['person','organization'],true)?$_POST['member_type']:'person','section'=>in_array(($_POST['section']??''),['council','secretariat','member'],true)?$_POST['section']:'member','name_zh'=>$nameZh,'name_ru'=>$nameRu,'name_en'=>$nameEn,'role_zh'=>trim((string)($_POST['role_zh']??'')),'role_ru'=>trim((string)($_POST['role_ru']??'')),'role_en'=>trim((string)($_POST['role_en']??'')),'organization_zh'=>trim((string)($_POST['organization_zh']??'')),'organization_ru'=>trim((string)($_POST['organization_ru']??'')),'organization_en'=>trim((string)($_POST['organization_en']??'')),'summary_zh'=>trim((string)($_POST['summary_zh']??'')),'summary_ru'=>trim((string)($_POST['summary_ru']??'')),'summary_en'=>trim((string)($_POST['summary_en']??'')),'bio_zh'=>trim((string)($_POST['bio_zh']??'')),'bio_ru'=>trim((string)($_POST['bio_ru']??'')),'bio_en'=>trim((string)($_POST['bio_en']??'')),'status'=>$status,'is_demo'=>isset($_POST['is_demo'])?1:0,'sort_order'=>(int)($_POST['sort_order']??100)];
            if($target>0){$sql='UPDATE members SET slug=:slug,member_type=:member_type,section=:section,name_zh=:name_zh,name_ru=:name_ru,name_en=:name_en,role_zh=:role_zh,role_ru=:role_ru,role_en=:role_en,organization_zh=:organization_zh,organization_ru=:organization_ru,organization_en=:organization_en,summary_zh=:summary_zh,summary_ru=:summary_ru,summary_en=:summary_en,bio_zh=:bio_zh,bio_ru=:bio_ru,bio_en=:bio_en,status=:status,is_demo=:is_demo,sort_order=:sort_order,updated_by=:uid,updated_at=:updated';if($photo!==null){$sql.=',photo_path=:photo';$fields['photo']=$photo;}$sql.=' WHERE id=:id AND deleted_at IS NULL';$fields['uid']=$user['id'];$fields['updated']=now_utc();$fields['id']=$target;db()->prepare($sql)->execute($fields);audit('member_update','member',$target,['status'=>$status]);}
            else{$fields['photo_path']=$photo??'';$fields['created_by']=$user['id'];$fields['updated_by']=$user['id'];$fields['created_at']=now_utc();$fields['updated_at']=now_utc();$columns=implode(',',array_keys($fields));$marks=':'.implode(',:',array_keys($fields));db()->prepare("INSERT INTO members ($columns) VALUES ($marks)")->execute($fields);$target=(int)db()->lastInsertId();audit('member_create','member',$target,['status'=>$status]);}
            flash('success','会员档案已保存。');redirect('/admin/members.php');
        }catch(PDOException $ex){$msg=str_contains($ex->getMessage(),'UNIQUE')?'该页面标识已存在，请更换。':'保存失败，请检查输入。';flash('error',$msg);redirect('/admin/members.php?action='.($target?'edit&id='.$target:'new'));}
        catch(RuntimeException $ex){flash('error',$ex->getMessage());redirect('/admin/members.php?action='.($target?'edit&id='.$target:'new'));}
    }
}

if($action==='new'||($action==='edit'&&$id>0)){
    $row=['id'=>0,'slug'=>'','member_type'=>'person','section'=>'member','name_zh'=>'','name_ru'=>'','name_en'=>'','role_zh'=>'','role_ru'=>'','role_en'=>'','organization_zh'=>'','organization_ru'=>'','organization_en'=>'','summary_zh'=>'','summary_ru'=>'','summary_en'=>'','bio_zh'=>'','bio_ru'=>'','bio_en'=>'','photo_path'=>'','status'=>'draft','is_demo'=>0,'sort_order'=>100];
    if($id>0){$s=db()->prepare('SELECT * FROM members WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);$row=$s->fetch()?:$row;}
    admin_header($id?'编辑会员档案':'新增会员档案',$user);?>
<section class="panel"><form method="post" enctype="multipart/form-data"><?=csrf_input()?><input type="hidden" name="operation" value="save"><input type="hidden" name="id" value="<?=(int)$row['id']?>"><div class="form-grid">
<div class="field"><label>页面标识 *</label><input name="slug" value="<?=e($row['slug'])?>" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="li-ming"><small>用于专属页链接，例如 members/li-ming.html</small></div><div class="field"><label>成员类型</label><select name="member_type"><option value="person" <?=$row['member_type']==='person'?'selected':''?>>个人</option><option value="organization" <?=$row['member_type']==='organization'?'selected':''?>>会员单位</option></select></div><div class="field"><label>所属板块</label><select name="section"><?php foreach(['council'=>'理事会','secretariat'=>'秘书处','member'=>'普通会员'] as $k=>$v):?><option value="<?=$k?>" <?=$row['section']===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></div><div class="field"><label>排序值</label><input type="number" name="sort_order" min="0" max="9999" value="<?=(int)$row['sort_order']?>"></div>
<?php foreach(['zh'=>'中文','ru'=>'俄文','en'=>'英文'] as $lang=>$label):?><div class="field"><label><?=$label?>名称 <?=$lang==='zh'?'*':''?></label><input name="name_<?=$lang?>" value="<?=e($row['name_'.$lang])?>" <?=$lang==='zh'?'required':''?> maxlength="160"></div><div class="field"><label><?=$label?>职务 / 类别</label><input name="role_<?=$lang?>" value="<?=e($row['role_'.$lang])?>" maxlength="180"></div><div class="field full"><label><?=$label?>单位</label><input name="organization_<?=$lang?>" value="<?=e($row['organization_'.$lang])?>" maxlength="220"></div><div class="field full"><label><?=$label?>卡片简介</label><textarea name="summary_<?=$lang?>" maxlength="700"><?=e($row['summary_'.$lang])?></textarea></div><div class="field full"><label><?=$label?>完整介绍</label><textarea name="bio_<?=$lang?>" maxlength="6000"><?=e($row['bio_'.$lang])?></textarea></div><?php endforeach;?>
<div class="field full"><label>照片 / 单位图片</label><input type="file" name="photo" accept=".jpg,.jpeg,.png,.webp"><small>支持 JPG、PNG、WebP，最大 5MB。</small><?php if($row['photo_path']):?><div class="file-note">已有图片：<?=e($row['photo_path'])?></div><?php endif;?></div><div class="field"><label>发布状态</label><select name="status"><option value="draft" <?=$row['status']==='draft'?'selected':''?>>草稿（不对外）</option><option value="published" <?=$row['status']==='published'?'selected':''?>>已发布</option></select></div><div class="field"><label><input type="checkbox" name="is_demo" value="1" <?=(int)$row['is_demo']===1?'checked':''?>> 标记为“演示资料”</label></div></div><div class="form-actions"><a class="btn" href="/admin/members.php">取消</a><button class="btn primary" type="submit">保存会员档案</button></div></form></section><?php admin_footer();exit;
}

$rows=db()->query('SELECT * FROM members WHERE deleted_at IS NULL ORDER BY section,sort_order,id DESC')->fetchAll();admin_header('会员资料',$user);?>
<section class="panel"><div class="panel-head"><div><h2>组织机构与会员档案</h2><small>每条已发布记录都对应一个公开专属页面</small></div><a class="btn primary" href="?action=new">+新增会员</a></div><div class="table-wrap"><table><thead><tr><th>名称</th><th>板块</th><th>职务/类别</th><th>页面标识</th><th>状态</th><th>操作</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><strong><?=e($row['name_zh'])?></strong><br><small><?=e($row['name_ru']?:$row['name_en'])?></small></td><td><?=['council'=>'理事会','secretariat'=>'秘书处','member'=>'会员'][$row['section']]?></td><td><?=e($row['role_zh'])?></td><td><code><?=e($row['slug'])?></code></td><td><?=status_badge($row['status'])?> <?=(int)$row['is_demo']===1?'<span class="badge">演示</span>':''?></td><td><div class="actions"><a class="btn small" href="?action=edit&id=<?=(int)$row['id']?>">编辑</a><?php if($row['status']==='published'):?><a class="btn small" href="/members/<?=e($row['slug'])?>.html" target="_blank">预览</a><?php endif;?><form class="inline-form" method="post"><?=csrf_input()?><input type="hidden" name="operation" value="delete"><input type="hidden" name="id" value="<?=(int)$row['id']?>"><button class="btn small danger" data-confirm="确认将该会员档案移入回收站？" type="submit">删除</button></form></div></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td class="empty" colspan="6">暂无会员档案。</td></tr><?php endif;?></tbody></table></div></section><?php admin_footer();
