<?php
declare(strict_types=1);require_once dirname(__DIR__).'/cms/bootstrap.php';$slug=slugify((string)($_GET['slug']??''));$s=db()->prepare("SELECT * FROM members WHERE slug=? AND status='published' AND deleted_at IS NULL LIMIT 1");$s->execute([$slug]);$m=$s->fetch();if(!$m){http_response_code(404);?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>未找到成员</title><link rel="stylesheet" href="../css/style.css"></head><body><main class="profile-page"><div class="container"><h1>未找到该成员资料</h1><p><a class="btn btn-gold" href="../members.html">返回协会成员</a></p></div></main></body></html><?php exit;}
function attrs(array $m,string $key):string{return 'data-zh="'.e($m[$key.'_zh']).'" data-ru="'.e($m[$key.'_ru']?:$m[$key.'_zh']).'" data-en="'.e($m[$key.'_en']?:$m[$key.'_zh']).'"';}
function member_initials(array $m):string{$parts=preg_split('/\s+/u',trim((string)$m['name_en']),-1,PREG_SPLIT_NO_EMPTY);if(count($parts)>1){return mb_strtoupper(mb_substr($parts[0],0,1).mb_substr($parts[count($parts)-1],0,1));}return mb_substr((string)($m['name_zh']?:'RC'),0,2);}
$section=['council'=>['理事会','Совет','Council'],'secretariat'=>['秘书处','Секретариат','Secretariat'],'member'=>['会员','Член ассоциации','Member']][$m['section']];?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?=e($m['summary_zh'])?>"><title <?=attrs($m,'name')?>><?=e($m['name_zh'])?> — 协会成员</title><link rel="stylesheet" href="../css/style.css?v=12"><link rel="icon" href="../img/favicon.png"><script src="../js/main.js?v=4" defer></script></head><body data-page="members">
<header class="site-header"><div class="header-inner"><a class="logo" href="../index.html"><img class="logo-img" src="../img/logo-mark.png" alt="RCECA"><span class="logo-text"><span class="logo-line1" data-zh="俄中电子商务协会" data-ru="Ассоциация «Россия — Китай»" data-en="Russia-China E-Commerce">俄中电子商务协会</span><span class="logo-line2">Russia-China E-Commerce Association</span></span></a><nav class="main-nav"><ul><li><a href="../index.html" data-zh="首页" data-ru="Главная" data-en="Home">首页</a></li><li><a href="../about.html" data-zh="关于协会" data-ru="Об ассоциации" data-en="About">关于协会</a></li><li><a class="active" href="../members.html" data-zh="协会成员" data-ru="Члены" data-en="Members">协会成员</a></li><li><a href="../resources.html" data-zh="资料中心" data-ru="Материалы" data-en="Resources">资料中心</a></li><li><a href="../contact.html" data-zh="联系我们" data-ru="Контакты" data-en="Contact">联系我们</a></li></ul></nav><div style="display:flex;align-items:center;gap:12px"><div class="lang-switch"><button class="lang-btn active" data-lang="zh">中文</button><button class="lang-btn" data-lang="ru">Рус</button><button class="lang-btn" data-lang="en">EN</button></div><button class="burger" aria-label="Menu"><span></span><span></span><span></span></button></div></div></header>
<main class="profile-page"><div class="container"><nav class="breadcrumb"><a href="../index.html" data-zh="首页" data-ru="Главная" data-en="Home">首页</a><span class="breadcrumb-sep">/</span><a href="../members.html" data-zh="协会成员" data-ru="Члены" data-en="Members">协会成员</a><span class="breadcrumb-sep">/</span><span <?=attrs($m,'name')?>><?=e($m['name_zh'])?></span></nav>
<?php if((int)$m['is_demo']===1):?><div class="demo-notice"><div class="demo-notice-mark">!</div><div><strong data-zh="演示资料 · 待秘书处确认" data-ru="Демонстрационные данны" data-en="Demo content · Confirmation required">演示资料 · 待秘书处确认</strong><span data-zh="本页为演示资料，不代表真实任职或会员关系。" data-ru="Данные вымышлены и не отражают реальное членство." data-en="This is fictional demo content and does not represent a real appointment or membership.">本页为演示资料，不代表真实任职或会员关系。</span></div></div><?php endif;?>
<section class="profile-hero-card" style="margin-top:24px"><div class="profile-portrait <?=$m['member_type']==='organization'?'profile-company-portrait':''?>"><?php if($m['photo_path']):?><img src="<?=e($m['photo_path'])?>" alt="<?=e($m['name_zh'])?>"><?php else:?><div class="company-mark <?=$m['member_type']==='person'?'profile-member-placeholder':''?>"><?=e(member_initials($m))?></div><?php endif;?></div><div class="profile-hero-copy"><div class="profile-kind" data-zh="<?=e($section[0])?>" data-ru="<?=e($section[1])?>" data-en="<?=e($section[2])?>"><?=e($section[0])?></div><h1 class="profile-name" <?=attrs($m,'name')?>><?=e($m['name_zh'])?></h1><div class="profile-role" <?=attrs($m,'role')?>><?=e($m['role_zh'])?></div><?php if($m['organization_zh']):?><div class="profile-meta"><span><i></i><b <?=attrs($m,'organization')?>><?=e($m['organization_zh'])?></b></span></div><?php endif;?><p class="profile-lead" <?=attrs($m,'summary')?>><?=e($m['summary_zh'])?></p></div></section>
<div class="profile-content"><section class="profile-panel"><h2 data-zh="成员简介" data-ru="Профиль" data-en="Member Profile">成员简介</h2><p <?=attrs($m,'bio')?>><?=e($m['bio_zh']?:$m['summary_zh'])?></p></section></div><div class="profile-back"><a class="btn btn-ghost" href="../members.html" data-zh="← 返回协会成员" data-ru="← Вернуться к членам" data-en="← Back to Members">← 返回协会成员</a></div></div></main><footer class="site-footer"><div class="container"><div class="foot-bottom">© <span data-year>2026</span> RCECA</div></div></footer></body></html>
